[package]
name = "bollox"
version = "0.1.0"
authors = ["gardrek <gardrek.the.destroyer@gmail.com>"]
edition = "2018"

[dependencies]
source-span = "2.7.0"
string-interner = "0.7.1"
lazy_static = "1.4.0"
