[package]
name = "bollox"
version = "0.2.0"
authors = ["gardrek <gardrek.the.destroyer@gmail.com>"]
edition = "2021"

[dependencies]
source-span = "2.7.0"
string-interner = "0.7.1"
lazy_static = "1.4.0"

[dependencies.clap]
version = "4.3.19"
features = ["derive"]